What2Eat/Models/ErrorViewModel.cs
using System;

namespace What2Eat.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

What2Eat/Models/EssenslisteModel.cs
namespace What2Eat.Models
{
    public class EssenslisteModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public bool Janic { get; set; }

        public bool Oma { get; set; }

        public bool Opa { get; set; }

        public string Suchwert { get; set; }
    }
}

What2Eat/Models/TodoListeModel.cs
namespace What2Eat.Models
{
    public class TodoListeModel
    {
        public string OffenePunkte { get; set; }

        //public string FertigePunkte { get; set; }
    }
}

What2Eat/Controllers/EssenslisteController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using What2Eat.Models;

namespace What2Eat.Controllers
{
    public class EssenslisteController : Controller
    {
        public string Suchwert { get; private set; }

        public IActionResult Index()
        {
            return View();
        }

        //public IActionResult Suche()
        //{
        //    Suchwert = new EssenslisteModel().Suchwert;

        //    return View(Suchwert);
        //}

        public IActionResult Essensliste()
        {
            List<EssenslisteModel> mahlzeiten = new List<EssenslisteModel>();
            mahlzeiten.Add(new EssenslisteModel { Id = 1, Name = "Croque", Janic = true, Oma = true, Opa = true });
            mahlzeiten.Add(new EssenslisteModel { Id = 2, Name = "Burger", Janic = true, Oma = true, Opa = true });
            mahlzeiten.Add(new EssenslisteModel { Id = 3, Name = "Chinesisch", Janic = false, Oma = true, Opa = true });

            return View(mahlzeiten);
        }
    }
}

What2Eat/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using What2Eat.Models;

namespace What2Eat.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

What2Eat/Controllers/TodoListeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using What2Eat.Models;

namespace What2Eat.Controllers
{
    public class TodoListeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult TodoListe()
        {
            List<TodoListeModel> punkte = new List<TodoListeModel>();

            punkte.Add(new TodoListeModel { OffenePunkte = "• Wochenplanung als Highlights auf der Startseite" });
            punkte.Add(new TodoListeModel { OffenePunkte = "• Liste mit Mahlzeiten und bool(mag ich) für jeden Mitesser" });
            punkte.Add(new TodoListeModel { OffenePunkte = "• Randomizer für den fall wenn man nicht weiß worauf man lust hat" });
            punkte.Add(new TodoListeModel { OffenePunkte = "• Bewertungsseite für jede Person" });
            punkte.Add(new TodoListeModel { OffenePunkte = "• Persönliche Logins für jeden Mitesser" });
            punkte.Add(new TodoListeModel { OffenePunkte = "• Details- Seite für jede Mahlzeit (never ending story)" });
            punkte.Add(new TodoListeModel { OffenePunkte = "• (Details) Rezept" });
            punkte.Add(new TodoListeModel { OffenePunkte = "• (Details) Zutaten" });
            punkte.Add(new TodoListeModel { OffenePunkte = "• (Details) Inhaltsstoffe" });
            punkte.Add(new TodoListeModel { OffenePunkte = "• User kann Haushalte erstellen und andere User zu diesen einladen" });

            return View(punkte);
        }
    }
}

What2Eat/Views/Essensliste/Essensliste.cshtml
@model IEnumerable<What2Eat.Models.EssenslisteModel>
@*@model What2Eat.Models.EssenslisteModel*@

@{
    ViewBag.Title = "Essensliste";
}

@*Header für jede View*@
<div class="text-center">
    <h1 class="display-4"><i class="fas fa-utensils"></i> Essensliste <i class="fas fa-utensils"></i></h1>
    <br />
    <br />
</div>
@*Header Ende*@

<br />
<br />
<form action="" class="">
    <div class="input-group mb-3">
        <input type="text" class="form-control" placeholder="Essen" />
        <button type="submit" class="input-group-text btn-dark"> <i class="bi bi-search me-2"></i> Suchen</button>
    </div>
</form>

<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.Id)</th>
        <th>@Html.DisplayNameFor(model => model.Name)</th>
        <th>@Html.DisplayNameFor(model => model.Janic)</th>
        <th>@Html.DisplayNameFor(model => model.Oma)</th>
        <th>@Html.DisplayNameFor(model => model.Opa)</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.Id)</td>
            <td>@Html.DisplayFor(modelItem => item.Name)</td>
            <td>@Html.DisplayFor(modelItem => item.Janic)</td>
            <td>@Html.DisplayFor(modelItem => item.Oma)</td>
            <td>@Html.DisplayFor(modelItem => item.Opa)</td>
        </tr>
    }

</table>

What2Eat/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@*Header für jede View*@
<div class="text-center">
    <h1 class="display-4"><i class="fas fa-utensils"></i> Essensplaner <i class="fas fa-utensils"></i></h1>
    <br />
    <br />
</div>
@*Header Ende*@

<div class="text-center">
    Bitte warten...
</div>

What2Eat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - What2Eat</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/4c4e5d962c.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="TodoListe" asp-action="TodoListe"><h3><i class="fas fa-utensils"></i></h3></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="TodoListe" asp-action="TodoListe">TO DO</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Essensliste" asp-action="Essensliste">Essensliste</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - What2Eat - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

What2Eat/Views/TodoListe/TodoListe.cshtml
@model IEnumerable<What2Eat.Models.TodoListeModel>

@{
    ViewData["Title"] = "TodoListe";
}

@*Header für jede View*@
<div class="text-center">
    <h1 class="display-4"><i class="fas fa-utensils"></i> TODOs <i class="fas fa-utensils"></i></h1>
    <br />
    <br />
</div>
@*Header Ende*@

<div class="text-center">

    <table class="table-borderless" align="center">
        <tr>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td align="left"><div align="center">@Html.DisplayFor(modelItem => item.OffenePunkte)</div></td>
            </tr>
        }
    </table>
</div>